---
  - name: Configurar NFS
    hosts: Centos
    become: yes

    tasks:
      - name: Instalar servidor NFS
        ansible.builtin.dnf:
          name: nfs-utils
          state: present

      - name: Iniciar y habilitar servicios
        ansible.builtin.service:
          name: nfs-server
          state: started
          enabled: true

      - name: Habilitar firewall para servicios
        ansible.posix.firewalld:
          port: 2049/tcp
          permanent: true
          state: enabled
          inmediate: true

      - name: Crear directorio
        ansible.builtin.file:
          path: /var/nfs_shared
          state: directory
          owner: nobody
          group: nobody
          mode: '0777'

      - name: Compartir directorio en /etc/exports
        ansible.builtin.lineinfile:
          path: /etc/exports
          line: "/var/nfs_shared *(rw,sync,no_root_squash)"
          state: present
          create: yes

    handlers:
      - name: Recargar NFS
        listen: "reload nfs"
        become: yes
        command: exportfs -ra    
